# Website Basic Information
baseURL = "https://blogis.athenalarm.com/"    # Placeholder URL, change to Cloudflare Pages URL after deployment
title = "Athenalarm Blogg"
languageCode = "is"
theme = "ananke"

# Author Information (optional)
[author]
  name = "Athenalarm"
  email = "info@athenalarm.com"

# Website Menu (optional)
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Heimasíða"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Greinar"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "contact"
    name = "Hafðu samband"
    url = "/contact/"
    weight = 3

# ---------------------------
# Home Page Settings
# ---------------------------
paginate = 5          # Heim síða sýnir nýjustu 5 greinar
mainSections = ["posts"]  # Heim síða sýnir aðeins greinar með type "posts"